### ISSUE TITLE
Update PACs to svd2rust v0.28.0 with --atomic option

### ISSUE THREAD

**Issue by n8tlarsen** [efm32-rs/efm32tg-pacs#1]
Hi, not sure what it would take to update all the PACs but svd2rust recently incorporated the stable 1.0 version of the portable_atomic crate, which would be nice to use in a number of applications. Happy to help with the update. I recently did the same for [ra-rs/ra](https://github.com/ra-rs/ra).

**Comment by vpetrigo** [comment]
See #2. All changes related to that issue should be available starting `0.1.2` (a5ca5cd66ba9e89b86fffdddc2d16836c594f16e)
