### ISSUE TITLE
Use svdtools to derive similar peripherals

### ISSUE THREAD

**Issue by n8tlarsen** [efm32-rs/efm32tg-pacs#4]
I've just started digging into using the PAC for real code and it would be nice when writing functions to control peripherals if similar peripherals shared the same types For example a function to control either TIMER0 and TIMER1 would be entirely the same code except for the type taken as the function parameter. SVD files and svd2rust have a mechanism to do this called `derivedFrom` (see [svd spec](https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_peripherals.html)). Unfortunately, SiLabs hasn't implemented this in their SVDs, but we can use [stm32-rs/svdtools](https://github.com/stm32-rs/svdtools) to help generate "patched" SVDs that allow svd2rust to generate the following for a derived peripheral:
``` rust
pub use self::timer0 as timer1;
```

**Comment by vpetrigo** [comment]
That would be great to have such an integration with the `svdtools`. I have been aware of this project, but currently have not had enough time yet to try SVD files patching.
If you are interested, I will be more than happy to accept a PR with SVD file patch for EFM32TG and update to [gen-tools](https://github.com/efm32-rs/gen-tools) that applies those patches before calling the `svd2rust` tool.

I assume that even a patch for a single MCU SVD would be great to start with. :smile:

**Comment by n8tlarsen** [comment]
I'll take a look at it!

**Comment by vpetrigo** [comment]
Since basic `svdtools` integration has been added to the `gen-tools` and you have authored the first batch of patches for the EFM32TG11B120, I guess that issue can be closed.
